### ISSUE TITLE
Release as Nextcloud app

### ISSUE THREAD

**Issue by sunjam** [icidasset/diffuse#107]
Nice music player!  It would be nice to be able to install the webdav version directly from the [Nextcloud appstore](https://apps.nextcloud.com).  [Here is a link to documentation.](https://nextcloudappstore.readthedocs.io/en/latest/)

Discussion thread created [here on help.nextcloud.com](https://help.nextcloud.com/t/diffuse-a-music-player-for-nextcloud-and-distributed-storage/32771)

**Comment by icidasset** [comment]
Thanks! ☺️ 
I will take a closer look at this soon.

**Comment by icidasset** [comment]
Part 1: https://github.com/nextcloud/app-certificate-requests/pull/160

**Comment by sunjam** [comment]
If Diffuse were successfully packaged as a Nextcloud app, Nextcloud admins could just click "install" from the internal appstore and then have Diffuse player available to them within their own private Nextcloud server.  [See the multimedia section of the app store here for examples](https://apps.nextcloud.com/categories/multimedia).  I enjoy Diffuse and would love to plug it directly into an existing Nextcloud (webdav) instance for playing my music.

[You can try out demo instances of Nextcloud here](https://help.nextcloud.com/t/demo-instances-of-9-10-11-and-12-now-live/8709).

I like that Diffuse makes it easy to add additional storage locations + Nextcloud makes it easy to share links, folders and music.

**Comment by icidasset** [comment]
Closing until further notice, NextCloud still hasn't done anything regarding CORS. Also don't want to maintain this appstore entry.
