### ISSUE TITLE
Support more file formats

### ISSUE THREAD

**Issue by icidasset** [icidasset/diffuse#110]
HTML5 Audio element supports these as well: wav, ogg, webm.

Note: UI should show notification when audio element in (older) browser does not support the file format.

I don’t know if there’s a Javascript library out there that can read any of these file formats.

**Comment by icidasset** [comment]
Will implement https://github.com/Borewit/music-metadata/issues/107 when available.

**Comment by Borewit** [comment]
[WebM](https://nl.wikipedia.org/wiki/WebM) is a video format, if you open an issue and include at least one  sample (with metadata), I can check if I can make it working. Opus, which is as well Ogg based, is supported.

Are you sure you need browser support? Most Electron based apps use the ability of Node.js to read the metadata:
- https://github.com/webtorrent/webtorrent-desktop/blob/master/src/renderer/webtorrent.js
- https://github.com/akabekobeko/examples-electron/blob/master/audio-player/src/js/main/MusicMetadataReader.js
- https://github.com/KeitIG/museeks
- https://github.com/IrosTheBeggar/mStream

**Comment by icidasset** [comment]
@Borewit Yeah, definitely. That's why I said "a Haskell library". I was thinking of https://github.com/lettier/webviewhs

I'm going to give it a try, thanks! 😄 
Not a webpack user here though, but I'll see what I can come up with.

**Comment by Borewit** [comment]
You maybe interested in the experimental browser version: [music-metadata-browser](https://github.com/Borewit/music-metadata-browser)

**Comment by icidasset** [comment]
@Borewit Awesome thanks! Will check it out soon, taking a little break at the moment.

**Comment by Borewit** [comment]
Should be good to go, let me know if you experience any issues.

**Comment by icidasset** [comment]
@Borewit Thanks for all the hard work you do! Really appreciated. But I was actually waiting on support for the range header 😅 I need to scan over 200GB of music, so it would be quite unfeasible to download all of that.

**Comment by Borewit** [comment]
Check: [streaming-http-token-reader](https://github.com/Borewit/streaming-http-token-reader).

Looking forward to hear from you is it meets your requirements.

**Comment by icidasset** [comment]
Implemented in #128
