### ISSUE TITLE
Audio is distorted using the Diffuse 1.0.0 Beta 5 on Debian 9 Amd64 with pulseaudio

### ISSUE THREAD

**Issue by e-alfred** [icidasset/diffuse#111]
Hello,

I am running Debian 9 Stretch AMD64 with Pulseaudio. If I try to play a track from a Nextcloud Webdav instance I get the message `Your internet connection got interrupted, click to resume.`and  distorted audio.

On the console I get the following error message:

```
:44999/lib/processing.js:27 Objectinfo: "No suitable tag reader found"type: "tagFormat"__proto__: Object
transformUrl.then.then.then.catch.e @ :44999/lib/processing.js:27
util.js:27 [object Object]
transformUrl.then.then.then.catch.e @ util.js:27
:44999/lib/processing.js:27 Object
transformUrl.then.then.then.catch.e @ :44999/lib/processing.js:27
util.js:27 [object Object]
transformUrl.then.then.then.catch.e @ util.js:27
audio-engine.js:236 Audio stalled for 'MTUyOTI0MTcxNzM5MTEvLy9vd25jbG91ZC9yZW1vdGUucGhwL3dlYmRhdi9tdXNpYy9BbmRyZWElMjBGZWRlbGkvT3ZlcmxhbmQlMjAxMiUyMF8lMjBOZWwlMjBDdW9yZSUyMGRlbGwlMjdBZnJpY2ElMjBOZXJhLzA0JTIwRWFnbGUlMjBIZWFydC5tNGE'
audioStalledEvent @ audio-engine.js:236
```

**Comment by icidasset** [comment]
Thanks for the report!

To be honest, I'm quite confused by NextCloud.
I tested the audio playback on a demo instance, which works fine (ie. `https://demo.nextcloud.com/...`).
And then tested it again on an instance on `indie.host`, which has the same issue as you described here 🤔 
Which version of NextCloud are you using?

The implementation of ranged HTTP requests is also quite odd, they don't have a `Accept-Ranges` header in the response, but it does return `Content-Range` when you request a range.

`</rant>` 😬 

I'm going to try again in a few days and see if I can come up with a decent solution then.

**Comment by icidasset** [comment]
Thanks again @e-alfred! 🙏 🙌 
I made a new beta release in which this should be fixed.
