### ISSUE TITLE
Google Play Music Support?

### ISSUE THREAD

**Issue by outpoints** [icidasset/diffuse#114]
So Google Play Music allows you to upload 50,000 songs for free, I was wondering if you could somehow make it link up to that and we could use that aswell?

**Comment by icidasset** [comment]
Hey @outpoints, thanks for the suggestion! Unfortunately 'Google Play Music' doesn't have a public API, so there's no way to integrate it.

Also, I'm not overly familiar with the service, so I was wondering what the bridge is that you're trying to gap? Why not, for example, upload those songs to Google Drive and add that to Diffuse?
