### ISSUE TITLE
Hangs on "Processing Tracks" with Azure Blob Storage

### ISSUE THREAD

**Issue by sbmw** [icidasset/diffuse#118]
Hi, I love the idea of this app and it works great with the demo library.  However, when I plug in the details of my Azure Blob Storage account I get no further than "Processing Tracks".  I've tried in both the web app with BlockStack and the latest native beta using Anonymous.  

There are 3300 blobs in the container. 

The dev tools console shows no errors in the web browser, but in the native app this error is logged:

Uncaught RangeError: Maximum call stack size exceeded
    at slave.js:9259
    at Function.func (slave.js:3129)
    at A2 (slave.js:92)
    at _eeue56$elm_xml$Xml_Decode$actualDecode (slave.js:9246)
    at slave.js:9251
    at Function.func (slave.js:3129)
    at A2 (slave.js:92)
    at _eeue56$elm_xml$Xml_Decode$actualDecode (slave.js:9246)
    at _eeue56$elm_xml$Xml_Decode$decode (slave.js:9238)
    at Function.func (slave.js:9206)

Thanks!

**Comment by icidasset** [comment]
Thanks @sbmw , will look into this!
Seems to be roughly the same issue as #112 🤔

**Comment by icidasset** [comment]
@sbmw I've updated the web version to scan max 1000 items at once, can you let me know if that fixes it? 🙏

**Comment by sbmw** [comment]
@icidasset Hey, thanks for the super fast turn around.  That max items restriction seems to work perfectly!
