### ISSUE TITLE
Which services should we integrate with?

### ISSUE THREAD

**Issue by icidasset** [icidasset/diffuse#12]
💁 Suggestions are welcome!

#### Music storage

- [x] [Amazon S3](https://aws.amazon.com/s3)
- [x] [Azure Blob Storage](https://azure.microsoft.com/en-us/services/storage/blobs/)
- [x] [Azure File Storage](https://azure.microsoft.com/en-us/services/storage/files/)
- [ ] ~~[Blockstack Gaia](https://blockstack.org/)~~
- [x] [BTFS](https://www.bittorrent.com/btfs/)
- [x] [Dropbox](https://www.dropbox.com/developers/documentation/http/documentation#files-list_folder)
- [x] [Google Drive](https://developers.google.com/drive/v3/reference/files/list)
- [x] [IPFS](https://ipfs.io)
- [ ] [Local](https://web.dev/native-file-system/) file system
- [x] [WebDAV](https://en.wikipedia.org/wiki/WebDAV)

_Maybe someday (if possible):_

- [Dat Protocol](https://datproject.org/)
- [LBRY](https://lbry.com/) (not sure if possible)
- [SeaFile](https://www.seafile.com/)
- [Sia storage](https://sia.tech/)
- [Soundcloud](https://soundcloud.com/) (not sure how this would work)
- [Storj](https://storj.io/api.html#buckets_get_buckets_id_files)
- [Torrents](https://webtorrent.io/docs) (streaming is difficult + CORS issues)
- [Youtube](https://www.youtube.com/) (not sure how this would work)
- [Wasabi](https://wasabi.com/)

_Cannot implement:_

- [One Drive](https://onedrive.live.com/about/)  
Too much of a hassle, requires use of an iframe and doesn't allow CORS with the code flow (refresh-token flow). Using an iframe is currently impossible and would mean rewriting a large part of the app.

#### Authentication / Information storage

- [x] Blockstack
- [x] IndexedDB
- [x] IPFS (v2)
- [x] RemoteStorage
- [ ] Solid (postponed, not enough tooling yet)
- [x] Textile (v2)

**Comment by theWebalyst** [comment]
I want to note here that if you support RemoteStorage using remoteStorage.js, it should become trivial to extend your support to SAFEnetwork (a decentralised secure autonomous Internet - see MaidSafe.net) using my fork of RS.js which is under development but working with the current SAFE Alpha2 network.

**Comment by jcmrva** [comment]
What about Azure blob storage?

**Comment by icidasset** [comment]
@jcmrva Thanks for the great suggestion! Will try to add that. Would you suggest https://azure.microsoft.com/en-us/services/storage/files/ as well then?

**Comment by jcmrva** [comment]
I hadn't considered it, but... maybe.

What about setting up a poll for these + priority?

**Comment by icidasset** [comment]
@jcmrva Sure thing!

In order of importance, more important -> less important:

[![](https://api.gh-polls.com/poll/01C9K65V24SBEW2H948V3RABN8/Azure%20Blob%20Storage)](https://api.gh-polls.com/poll/01C9K65V24SBEW2H948V3RABN8/Azure%20Blob%20Storage/vote)
[![](https://api.gh-polls.com/poll/01C9K65V24SBEW2H948V3RABN8/Azure%20File%20Storage)](https://api.gh-polls.com/poll/01C9K65V24SBEW2H948V3RABN8/Azure%20File%20Storage/vote)
[![](https://api.gh-polls.com/poll/01C9K65V24SBEW2H948V3RABN8/Storj)](https://api.gh-polls.com/poll/01C9K65V24SBEW2H948V3RABN8/Storj/vote)

**Comment by icidasset** [comment]
@jcmrva Do you by any chance have any experience with the Azure APIs? I did most of the integration work, but I keep getting an authorization error. See #90 for more info (in case you're interested).

**Comment by jcmrva** [comment]
A little... I'll look into it when I get home next week if it's still open.

**Comment by icidasset** [comment]
@jcmrva Never mind, found the issue. Support for 'Azure Blob Storage' has been added 👍I'm going to add the 'Azure File Storage' integration later, because that one is a bit more difficult. The file storage API doesn't support recursive listing of "shares" so I will have to build my own strategy for this.

**Comment by sunjam** [comment]
It would be fun to federate to other instances of Diffuse using [ActivityPub.](http://activitypub.rocks)
You could also federate with [Funkwhale](https://funkwhale.audio) (similar to Grooveshark) which is also working on federation on their [Gitlab](https://code.eliotberriot.com/funkwhale/funkwhale).

Activitypub is what Nextcloud uses to federate with other instances afaik.  [Peertube video platform](https://github.com/Chocobozzz/PeerTube) as well.  [Checkout this video of Peertube federating with Mastodon social platform](https://github.com/Chocobozzz/PeerTube).

**Comment by icidasset** [comment]
@sunjam Thanks again! 🙏 

I will look into WebTorrent when I have time, cool to see that is possible!
Added Sia to the list.

Could you explain your reason for suggesting ActivityPub?
Is there a specific feature you are looking for?

I was thinking to do something with multiple instances.
For example, one thing I had in mind was that you could crossfade to a different instance.
Would be cool for DJ-ing.

That said, I'm not entirely getting this "federate" thing yet.
I'll have to look more into ActivityPub first I assume.

**Comment by ciperyon** [comment]
Any love for simple OneDrive?

**Comment by icidasset** [comment]
@ciperyon Thanks for the suggestion, added it to the todo list.

**Comment by icidasset** [comment]
Update on One Drive:
Currently not able to implement as the "code flow" authentication procedure does not support CORS. They suggest using an iframe as an alternative, but I'm not going anywhere near an iframe.

**Comment by sunjam** [comment]
[Oauth2 support](https://docs.nextcloud.com/server/14/admin_manual/configuration_server/oauth2.html) would be nice.  Then I could log into Diffuse directly from Nextcloud or even this Github account.

**Comment by icidasset** [comment]
@sunjam Thanks for the suggestion! Sorry for the late reply. I'm not sure how that would work, since you have to register oauth applications, right? I'd like the application to be completely independent of other services.
