### ISSUE TITLE
Missing Elm dependencies `spisemisu/elm-sha` and `spisemisu/elm-utf8`

### ISSUE THREAD

**Issue by AdrianoFerrari** [icidasset/diffuse#121]
How to reproduce:
* Delete elm-stuff directory
* `make`

Note, I got burned by this in my own project, but didn't notice for a while because local `elm-stuff` had package from when it was still online.

Will hit missing packages https://github.com/spisemisu/elm-sha and https://github.com/spisemisu/elm-utf8:
![screenshot_2018-07-11_14-05-41](https://user-images.githubusercontent.com/323678/42591105-a96481ca-8513-11e8-9555-adb583b7f451.png)

**Comment by icidasset** [comment]
Fix in #122
