### ISSUE TITLE
Azure File Storage gives 'ConditionHeadersNotSupported' error in Chrome

### ISSUE THREAD

**Issue by icidasset** [icidasset/diffuse#123]
Occurs when processing the source.

```xml
<?xml version="1.0" encoding="utf-8"?><Error><Code>ConditionHeadersNotSupported</Code><Message>Condition headers are not supported.
RequestId:f2db3393-e01a-0030-0733-1c0c10000000
Time:2018-07-15T12:04:14.6590122Z</Message></Error>
```

Seems to do with the caching strategy that Chrome uses.
No issues in Firefox and Safari.

No clue how to fix 👎

**Comment by icidasset** [comment]
**Disabled this source type until further notice.**
No idea how to fix.

**Comment by rahatur** [comment]
@icidasset can you please let us know what you meant by "Disabled this source type"?
Can you please share a sample code?

**Comment by icidasset** [comment]
@rahatur "Disabled" as in you can no longer add a new "Azure File Storage" source, but you can still continue to use an existing one. Not sure what you mean with "a sample code".
