### ISSUE TITLE
Hide duplicate songs

### ISSUE THREAD

**Issue by ReleaseTheKnowledge** [icidasset/diffuse#132]
I have Diffuse setup to use local storage, and WebDAV from Nextcloud. But some of the songs are the same on Nextcloud and Local. Would love a way to automatically hide all the duplicates. Thanks!

**Comment by icidasset** [comment]
@ReleaseTheKnowledge Thanks for the suggestion! Will definitely add this in version 2, which is currently in the works.

**Comment by icidasset** [comment]
Implemented in #128
