### ISSUE TITLE
Add screen with extra info that can be shown using keyboard shortcut

### ISSUE THREAD

**Issue by icidasset** [icidasset/diffuse#134]
Info:
- Sorting algorithm used (eg. first album, then track number, ...)
- Amount of tracks/favourites/playlists in collection (extra: group by source?)
- Amount of search results
- Amount of duplicates (maybe show this in settings instead)
- Technical info about currently-playing track
- Current EQ settings
- Current Queue settings
- Enabled settings
- ...

Inspiration:
- https://aphextwin.warp.net/

**Comment by lpil** [comment]
How do we bring up this extra info? :)

**Comment by icidasset** [comment]
@lpil Never actually implemented this sorry 😅 

What part of this did you like?
If you were just looking for an overview of the keyboard shortcuts,
there's a list on the about page under "Keyboard" https://diffuse.sh/about#UI

Upcoming v3 will have more shortcuts (eg. to bring up an autocomplete textfield to select a playlist)

**Comment by lpil** [comment]
I wasn't looking for anything specific, I was mostly just exploring what the software can do. Thanks! :)

By the way, I really like the technical decisions you've made here, very cool!
