### ISSUE TITLE
Where would you preferably store your application data?

### ISSUE THREAD

**Issue by icidasset** [icidasset/diffuse#136]
If you had to choose a place to store your application data (not music) from Diffuse, where would it be?
**Note that all data will be encrypted using a passcode of your choice.**

_Choose one of the following:_

[![](https://api.gh-polls.com/poll/01D1Y7F4BEMQ6YD4E76WHEFTJM/IPFS)](https://api.gh-polls.com/poll/01D1Y7F4BEMQ6YD4E76WHEFTJM/IPFS/vote)
[![](https://api.gh-polls.com/poll/01D1Y7F4BEMQ6YD4E76WHEFTJM/Dropbox%2C%20Google%20Drive%2C%20One%20Drive%2C%20etc.)](https://api.gh-polls.com/poll/01D1Y7F4BEMQ6YD4E76WHEFTJM/Dropbox%2C%20Google%20Drive%2C%20One%20Drive%2C%20etc./vote)
[![](https://api.gh-polls.com/poll/01D1Y7F4BEMQ6YD4E76WHEFTJM/Blockstack)](https://api.gh-polls.com/poll/01D1Y7F4BEMQ6YD4E76WHEFTJM/Blockstack/vote)
[![](https://api.gh-polls.com/poll/01D1Y7F4BEMQ6YD4E76WHEFTJM/A%20%22RemoteStorage%22%20server)](https://api.gh-polls.com/poll/01D1Y7F4BEMQ6YD4E76WHEFTJM/A%20%22RemoteStorage%22%20server/vote)
[![](https://api.gh-polls.com/poll/01D1Y7F4BEMQ6YD4E76WHEFTJM/A%20%22Solid%22%20pod)](https://api.gh-polls.com/poll/01D1Y7F4BEMQ6YD4E76WHEFTJM/A%20%22Solid%22%20pod/vote)
[![](https://api.gh-polls.com/poll/01D1Y7F4BEMQ6YD4E76WHEFTJM/Other%20(suggestions%20welcome!))](https://api.gh-polls.com/poll/01D1Y7F4BEMQ6YD4E76WHEFTJM/Other%20(suggestions%20welcome!)/vote)

**Comment by expede** [comment]
What is this voting magic? ✨

**Comment by icidasset** [comment]
@expede https://app.gh-polls.com/ ✨

**Comment by michaelsena** [comment]
3Box is another option worth considering here. 3Box provides a simple user-centric middleware layer between IPFS and apps, that makes app data stored on IPFS interoperable and shareable by associating it with the user. https://github.com/3box/3box

**Comment by icidasset** [comment]
Thanks @michaelsena , will definitely check out 3Box 😉

**Comment by icidasset** [comment]
Will try to add as many as possible in V2.
That said, it'll relatively easy for someone to make a PR to add an additional storage service.
