### ISSUE TITLE
mp4 format music cannot tracked

### ISSUE THREAD

**Issue by gitkiwikiwi** [icidasset/diffuse#138]
I stored the mp4 and mp3 in the same dropbox folder, why did not mp4 form be found in the track of diffuse?

**Comment by icidasset** [comment]
Hi @gitkiwikiwi 

It definitely works with files that have the m4a extension.
It should also work with the mp4 extension, but not 100% sure.

That said, it could be that it has trouble reading the metadata/tags from the file.
In that case you would see an error in the browser console. These errors roughly look like this:

<img width="705" alt="screen shot 2019-02-14 at 20 52 29" src="https://user-images.githubusercontent.com/296665/52813694-a30ac680-309a-11e9-8519-1e259104df16.png">

You could also send me the mp4 file if you want to.

**Comment by gitkiwikiwi** [comment]
![2019-02-15 12 33 57](https://user-images.githubusercontent.com/43330823/52834743-494be000-311e-11e9-8171-5e2af62337ad.png)
Here are the console displayed, I put 2 mp4 format and 3 mp3 format songs in my dropbox,in the same folder,however , only 2 of the mp3 format can be read.

**Comment by gitkiwikiwi** [comment]
mp4 is a video format, can this site code read it from dropbox with all videos format? What is your email address,I can share this dropbox folder address to you.

**Comment by icidasset** [comment]
Thanks @gitkiwikiwi , that doesn't seem right 😅 
My email address is `icid.asset@gmail.com`.

**Comment by gitkiwikiwi** [comment]
1. I shared the blockstackmp3 folder to you
2. Another bug I found,if I tried to remove the old sources from the
settings, next time, when I open a new webpage ,that old source would came
up again. Something wrong with the cookies?And I tried rename the
directory  from the setting, it would not works.

Steven Vandevelde <notifications@github.com> 于2019年2月15日周五 下午9:05写道：

**Comment by icidasset** [comment]
Thanks @gitkiwikiwi
It's probably an issue with Blockstack, haven't updated that in a while.
I'll see what I can do.

**Comment by icidasset** [comment]
Huh, that's odd, I'm getting totally different results.

<img width="905" alt="screenshot 2019-02-16 at 13 47 23" src="https://user-images.githubusercontent.com/296665/52900059-b2e8ee80-31f1-11e9-982e-1297bf88dd3e.png">

Those 2 tracks named "Unknown" are the mp4 files.
Those mp4 files don't have any IDv3 metadata, that why it says "Unknown".
The missing mp3 file `beonyou.mp3` can't be processed, it looks like the metadata is missing.
So maybe you could use a IDv3 tag editor (eg. https://www.nightbirdsevolve.com/meta/) to fix it.

Few question for you:
1. Are you using the "app" or the website "https://diffuse.sh/"?
2. In case you're using the website, which browser?
3. Which option did you pick to "sign in"? (I assumed Blockstack, but let me know if I assumed wrong)

**Comment by icidasset** [comment]
PS. Just making a note here. When you remove a source, it takes 5 to 10 seconds to save the changes. So when you close the window in that time frame, the source will not be removed.

**Comment by icidasset** [comment]
Closing this, reopen if you want to discuss further @gitkiwikiwi
