### ISSUE TITLE
Improve remoteStorage experience

### ISSUE THREAD

**Issue by bmann** [icidasset/diffuse#141]
I was not familiar with remoteStorage. I went to try Diffuse, selected remoteStorage, and put in my email address. Then it failed silently because my email address is not a remoteStorage account, and I was back at the login screen, with no feedback on failure.

For now, I would have an error message "That doesn't look like a remoteStorage ID" that then has a link to remoteStorage providers or more info.

**Comment by icidasset** [comment]
That's definitely bad UI, thanks for making this issue! ☺️ 
Will be addressed in V2.

**Comment by icidasset** [comment]
Implemented in #128
