### ISSUE TITLE
make: *** [elm] Error 1

### ISSUE THREAD

**Issue by montuIO** [icidasset/diffuse#145]
When running make I get this error.

> Cleaning Build Directory
> Compiling Elm
make: elm-make: No such file or directory
make: *** [elm] Error 1

**Comment by icidasset** [comment]
Hi @montuIO. You'll need to install [elm](https://elm-lang.org/) (version 0.18, not the latest) if you want to build it yourself. FYI, there's a pre-built web version of Diffuse on the releases page called [`Diffuse-1.0.2-web.zip`](https://github.com/icidasset/diffuse/releases).

Let me know if you have any other questions.
