### ISSUE TITLE
Connect to Nextcloud via WebDAV problems

### ISSUE THREAD

**Issue by agiz10** [icidasset/diffuse#154]
Hi,
I just tried connecting to my Nextcloud installation (latest 16.0.4) with latest Diffuse (2.0.0.), but can not seem to get it working.

I am using Windows app:
`Cannot connect to this source`
Inbuilt debugger is showing me this:
`Access to XMLHttpRequest at 'https://somehost.com/remote.php/dav/files/username' from origin 'http://127.0.0.1:44999' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

What am i doing wrong and how can i fix it?

Thank you.

**Comment by icidasset** [comment]
Hi @agiz10 👋 

So, like the warning in the app says, the WebDAV server **needs to implement CORS** properly. I think Nextcloud still hasn't done this, as the [issue on the Nextcloud repo](https://github.com/nextcloud/server/issues/3131) is still open. There are [some solutions](https://github.com/nextcloud/server/issues/3131#issuecomment-489179454) in that issue you could look at though.

I hope this helps ✌️

**Comment by icidasset** [comment]
I've had other people asking about this, so I'll clear things up here while I'm at it. The native version of `v1` ignored the CORS restrictions by shoving all WebDAV requests through a proxy server that was running along side the app.

I've removed this behaviour in `v2` to make the app easier to maintain and have the native variant identical to the web variant. I also think that WebDAV clients should properly implement all HTTP-related protocols, seeing that WebDAV is an extension of HTTP.

If you want to check out the old version, you can find it here: https://github.com/icidasset/diffuse/releases/tag/1.0.2

**Comment by agiz10** [comment]
Thank you for clarification.
Old client indeed works well with Nextcloud.

I did not try the proxy suggestion/nginx workaround you mentioned.

**Comment by Glandos** [comment]
The new plugin from [this comment](https://github.com/nextcloud/server/issues/3131#issuecomment-598866074) is working like a charm with diffuse.
It is available (for now) only at https://gitlab.com/kinolaev/nextcloud-dav-cors
