### ISSUE TITLE
Search using russian or non-alphanumeric characters

### ISSUE THREAD

**Issue by EugeneNeuron** [icidasset/diffuse#165]
Tracks named in russian aren't searchable. And at least some non-alphanumeric characters as well (e.g. dollar sign).
I tried to search for example song "Твой Первый День" written by "7000$". When I searched "7000" - song was found, but "7000$" or "Твой Первый День" didn't work out.

**Comment by EugeneNeuron** [comment]
Nightly version really does the job perfectly.
I also emailed you an example track.

Thanks!

**Comment by icidasset** [comment]
Just released v2.1 and update diffuse.sh with the fix.
