### ISSUE TITLE
[FR] Android standalone client

### ISSUE THREAD

**Issue by ildar** [icidasset/diffuse#178]
Sorry, this may be offtopic for this repo.
I'd be happy to see an Android standalone client or a plugin to some existing Android player. Using browser for that is still a poor UX.

**Comment by icidasset** [comment]
I wouldn't mind seeing standalone clients for mobile either. That said, I don't really do mobile dev, nor do I have the time to do this. I also don't have an Android device, so I don't have any input on that front.

What are you expecting from a standalone mobile client? A better UX, ie. a mobile targeted design? If yes, what specifically bugs you in the browser version?

**Comment by ildar** [comment]
mere things that a user expects from a Music player:
  [ ] Prev/Next control buttons on the lock screen
  [ ] Multimedia control buttons on the headphones
  [ ] (usually) smaller memory footprint then a big fat browser

**Comment by icidasset** [comment]
I totally get that, I like those features as well 🙏 

The first two items should be addressed as PWA's get more prominent in the mobile space. I've already (partially) implemented the [Media Session API](https://developer.mozilla.org/en-US/docs/Web/API/Media_Session_API) which should allow those two things. Well, it says it's supported on Chrome for Android, I never got the chance of actually testing it on an Android device. Hopefully soon! I need to find a cheap but good Android device 🤔

**Comment by icidasset** [comment]
Firefox is starting to implement the Media Session API as well. Will continue on that path.
