### ISSUE TITLE
last.fm: unencrypted http request blocked by chromium

### ISSUE THREAD

**Issue by fphammerle** [icidasset/diffuse#195]
Follow-up after https://github.com/icidasset/diffuse/issues/190

Thanks @icidasset for integrating last.fm scrobbling!

I just tried to connect to last.fm via the "Connect" button in "Settings" at https://nightly.diffuse.sh

After authorizing diffuse I got redirected back to https://nightly.diffuse.sh/?action=authenticate/lastfm&token=***

 A popup "Could not connect with Last.fm" with red background appeared on the bottom right

The console shows:
```
ui.elm.js:1 Mixed Content: The page at 'https://nightly.diffuse.sh/?action=authenticate/lastfm&token=***' was loaded over HTTPS,
but requested an insecure XMLHttpRequest endpoint 'http://ws.audioscrobbler.com/2.0?api_key=***&api_sig=***&format=json&method=auth.getSession&token=***'.
This request has been blocked; the content must be served over HTTPS.
```

Could you maybe adapt the endpoint to use https?

```sh
$ apt version chromium-browser
79.0.3945.79-0ubuntu0.18.04.1
```

**Comment by icidasset** [comment]
Thanks for testing this so quickly! ☺️ 

It should use HTTPS now 👍 
Forgot that Firefox still allows this.

**Comment by fphammerle** [comment]
Thanks a lot!
