### ISSUE TITLE
Add Diffuse to Nextcloud app store

### ISSUE THREAD

**Issue by sunjam** [icidasset/diffuse#211]
[Now possible to add Diffuse as a third party desktop app in the Nextcloud store so people can more easily find it](https://github.com/nextcloud/appstore/issues/95#issuecomment-621959723).  Thanks for making this. :heart: 

![](https://user-images.githubusercontent.com/4741199/80734694-d440ac80-8b0f-11ea-9d61-2f8b02722e64.png)

**Comment by icidasset** [comment]
Thanks @sunjam! ☺️ Was able to register the app 👍 Will upload `v2.5.0` when it's ready.

**Comment by icidasset** [comment]
Ok, finally got it on there: https://apps.nextcloud.com/apps/diffuse
That was difficult 😅 

I assume you can add screenshots and what not, but I don't have the time to look into all that. So if anyone can make a PR for that, that'd be great. The info file can be found here: https://github.com/icidasset/diffuse/blob/master/src/Static/Manifests/Nextcloud/appinfo.xml

**Comment by sunjam** [comment]
> Ok, finally got it on there: https://apps.nextcloud.com/apps/diffuse
> That was difficult 😅

Hmm, perhaps when you have a moment you can let them know what was painful over on https://github.com/nextcloud/appstore/issues/95#issuecomment-608074383
