### ISSUE TITLE
Nextcloud Integration wont connect

### ISSUE THREAD

**Issue by Loigzorn** [icidasset/diffuse#218]
I have tried to setup this serverless tool to listen to music on my PC,
I tried to use therefore the Nextcloud Diffuse App, which you can integrate to your Nextcloud instance.
After doing so I found no setup page on the admin view of Nextcloud, so I thought I may only need to install a client to be ready to go.
But in the client (application or website) i wasn't able to log on to my Nextcloud instance.
Am I missing something? Maybe some configuration that needs to be done?

Nextcloud Diffuse App version: 2.5.3
Nextcloud version: 18.0.4
Client Diffuse App version: 2.5.3

**Comment by icidasset** [comment]
Hi, thanks for trying out the app 👋 

You can't log in with Nextcloud (yet).
You can, however, log in with the other options and then play your music from your Nextcloud by connecting to it using WebDAV.

_I assume it probably doesn't make much sense from a Nextcloud perspective. TBH, the only reason I put the app on the Nextcloud app store is because some recommended it to me._

That said, suggestions are welcome. And, I need to look into using WebDAV for the "login" (aka. user-data storage layer), but not sure if that's possible.

**Comment by Loigzorn** [comment]
Hey, thank you for replaying so fast!

I would like to see a feature to be able to connect my Nextcloud instance to your service.
On my side I was for most looking for a new way of playing music stored on my cloud.
However I can see that this way of using it may hasn't been considered yet.

Your service already is looking like a solid application to my that could by useful for many.
In my case, I am trying to stay away from public cloud services, so connecting through a different could service to be able to  access Nextcloud is not an option for me.

I don't have much experience with the Nextcloud apt, but what difficulties are you facing with logging is form Nextcloud to your service?

Greetings

**Comment by icidasset** [comment]
Well, you can play your music stored on your Nextcloud already, using [WebDAV](https://duckduckgo.com/?t=ffab&q=nextcloud+webdav&atb=v189-1&ia=web).
There are no other protocols Nextcloud provides, right? (ie. besides WebDAV)

> but what difficulties are you facing with logging is form Nextcloud to your service?
No difficulties, just haven't had the time to research that part.
Specifically, I haven't checked if I can do the login part with WebDAV as well.

**Comment by Loigzorn** [comment]
Yes there are several ways of playing audio files that are stored on Nextcloud. 
Nextcloud has an app where you can play files on your browser, see this link:
[https://docs.nextcloud.com/server/15/developer_manual/client_apis/LoginFlow/index.html](url)

There is even a client for android and ios: [https://www.cloudbeatsapp.com/](url)
But non of these solutions has satisfied me. 

Your solution has a very well designed UI, so I thought this could be the one I was looking for.

> There are no other protocols Nextcloud provides, right? (ie. besides WebDAV)
Not to my knowledge, at least not for the purposes of the tools provided by WebDAV.
Although there is a procedure documented to cover the login process: 
[https://docs.nextcloud.com/server/15/developer_manual/client_apis/LoginFlow/index.html](url)

**Comment by pmk1c** [comment]
I think the first useful thing would be to have a link in the Nextcloud menu, so we can just access Diffuse. I installed the app and I can't see anything like that - am I just blind?

Your app looks great. Would like to test this on my Nextcloud instance.

**Comment by icidasset** [comment]
@Loigzorn Thanks for the resources/links and the kind words ✌️ 

I'll take a look at those login docs soon.

---

@pmk1c You're most likely not blind 😄 I don't use NextCloud myself, so pretty sure I haven't done the necessary steps to add it to that menu you mentioned.

I'll try looking into this soon, so any resources are welcome (eg. how to add my app to that menu).

Thanks for the feedback!

**Comment by icidasset** [comment]
Tracking login and additional integrations in #233
