### ISSUE TITLE
IPFS Companion subdomain (proxy) is not considered a secure context

### ISSUE THREAD

**Issue by fabrixxm** [icidasset/diffuse#241]
When signing in using a password, nothing shows up other than the spinner, and in console I get this

```
TypeError: b.subtle is undefined brain.js:29:126698
    fabricateSecretKey http://diffuse.sh/brain.js#appHref=http://diffuse.sh/#/settings:29
    fabricateSecretKey http://diffuse.sh/brain.js#appHref=http://diffuse.sh/#/settings:29
    c http://diffuse.sh/brain.elm.js:1
    s http://diffuse.sh/brain.elm.js:1
    b http://diffuse.sh/brain.elm.js:1
    Jr http://diffuse.sh/brain.elm.js:1
    zr http://diffuse.sh/brain.elm.js:1
    Wr http://diffuse.sh/brain.elm.js:1
    bn http://diffuse.sh/brain.elm.js:1
    sn http://diffuse.sh/brain.elm.js:1
    v http://diffuse.sh/brain.elm.js:1
    send http://diffuse.sh/brain.elm.js:1
    onmessage http://diffuse.sh/brain.js#appHref=http://diffuse.sh/#/settings:29
    (Asinc.: EventHandlerNonNull)
    <anonima> http://diffuse.sh/brain.js#appHref=http://diffuse.sh/#/settings:29
    r http://diffuse.sh/brain.js#appHref=http://diffuse.sh/#/settings:1
    <anonima> http://diffuse.sh/brain.js#appHref=http://diffuse.sh/#/settings:1
    <anonima> http://diffuse.sh/brain.js#appHref=http://diffuse.sh/#/settings:1
```

**Comment by icidasset** [comment]
@fabrixxm Hi 👋 

It looks like you're using `http://`, Diffuse only works on HTTPS.
I really need to set up auto redirect to https 🤔 

Thanks for the bug report!

**Comment by fabrixxm** [comment]
so it will not work on IPFS with a local gateway...

**Comment by icidasset** [comment]
Hmm, good question.

So, bit more context, you're getting error because you're not in a "secure context". Which normally means you're not using HTTPS. But, localhost is also considered a secure context, so local gateway should work. 

Are you using IPFS companion?
What do those new "proxy domains" look like, it's not localhost anymore is it? 🤔

**Comment by fabrixxm** [comment]
Yes, I'm using IPFS companion, the url of the webapp with the local gateway is http://diffuse.sh.ipns.localhost:8080/

**Comment by icidasset** [comment]
Thanks! I'll see if I can find a way around this. Most likely cause of this is that the browser doesn't think this is a secure context. This used to work, but then IPFS companion switched to this subdomain proxy pattern.

Workarounds:
- Don't use the proxy provided by IPFS companion (ie. use `https://diffuse.sh` as normal)
- I'm not sure this'll work, but try to use the app without encryption (ie. `Continue without encryption` under big button)

**Comment by fabrixxm** [comment]
>     * I'm not sure this'll work, but try to use the app without encryption (ie. `Continue without encryption` under big button)

yes, that works

**Comment by icidasset** [comment]
In the upcoming version it'll show a message if the context is insecure. That said, this `http://diffuse.sh.ipns.localhost:8080/` address should work fine with the current version on Chrome. And soon on Firefox: https://twitter.com/dietrich/status/1326004687133433857
