### ISSUE TITLE
A few questions, issues and suggestions

### ISSUE THREAD

**Issue by Pheggas** [icidasset/diffuse#261]
I found out this project to be very lightweight and useful. So i have some questions:

~~Does this support .flac formats and .cue sheet for .flac files? If not, this may be a suggestion.~~ Not at all. Support would be welcome
Will it handle RPI? (Raspberry Pi if you haven't heard)
What about caching? Does it support non caching direct play from e.g. Google Drive (and without delay before playback)?

Issues:
- I don't host it yet but from the demo, i have some frontend suggestions.
- The progress bar is really unspottable (if that is a word). With current bacground and thickness of the bar it's really pain to see or rewind the song.
- The search engine refreshes results after user action other than typing letters so you need to press enter.
- The search can't find part of the word in the name of the song. Eg.: You have there "Essential Mix"; I type Ess and it can't find it.
- Some of the text is unreadable on different backrounds (maybe outer border of the text will help)
- Time playing. I can't see anywhere the time of the song or the current time in the song.

Suggestions:
- Please, add login. It would be very useful for multi user access. Or even registration and request of approval from Admin of the server.
- Streaming same song between all (or group of) devices connected to that web app. Let's say i'll create user group and in this group i can play any song or playlist and all users connected will have synced playing.
~~Please, add Interpret and album sections :)~~ (spotted it has been added to nightly version of Diffuse)

Overall i'm very impressed of this web app, very minimal, lightweight. All i want to have! Great job so far!

Edit: Go fix your Source tab on demo. Well, the secret and access key is as password so nothing has been shown (yet) but everyone can retype that type:password to text and copy your access.

**Comment by icidasset** [comment]
Thanks @Pheggas ! ☺️ 

`.flac` should be supported, but it depends on the browser if it can be played.
https://caniuse.com/?search=flac Looks like most browsers support it now.
Haven't tested this in a long time though, I'll try it myself soon.

> Will it handle RPI?

It's a web application, so I guess so?

> What about caching?

It should preload the next track in the queue.
And you can download tracks for offline usage (by opening context menu, right click or touch hold).

> I don't host it yet but from the demo

diffuse.sh is not a demo instance, it is the application itself, no need to host it yourself. But you can if you really want to.

> The search engine refreshes results after user action other than typing letters so you need to press enter.
> The search can't find part of the word in the name of the song

Great feedback, thanks!

> Please, add login. It would be very useful for multi user access.

Will be added in the future through https://fission.codes/

> Edit: Go fix your Source tab on demo. Well, the secret and access key is as password so nothing has been shown (yet) but everyone can retype that type:password to text and copy your access.

I know, no worries, this key pair only has read access.

Regarding all other feedback, I'll think about it. Thanks again! ✌️

**Comment by icidasset** [comment]
Confirmed that flac works on Firefox & Chromium browsers.

**Comment by icidasset** [comment]
Improved seach as well, now supports incomplete terms.
