### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by icidasset** [icidasset/diffuse#270]
- [x] PWA not available offline (broken?)
- [ ] Spacing issue at the bottom (Chrome on Android)
- [ ] Active playlist name is not readable with certain backgrounds

**Comment by 4DA** [comment]
From help:

![image](https://user-images.githubusercontent.com/364499/109869505-006e1200-7c7a-11eb-9d7b-a5e74bcf4c74.png)

There is a problem with this setup that, it doesn't include allow access from webui or local http endpoint, which will break local ipfs node setup.

I guess tt should be changed to something like this:
 
```
        "Access-Control-Allow-Origin": [
            "http://127.0.0.1:5001",
            "https://webui.ipfs.io",
            "http://localhost:3000",
            "https://diffuse.sh",
            "http://diffuse.sh.ipns.localhost:8080",
            "http://127.0.0.1:44999"
        ]
```

**Comment by icidasset** [comment]
Thanks @4DA ! Yeah, my message is confusing, it was meant to be an addition to the existing URLs in that list. I didn't want to put the entire list in there, because (1) it takes up more space, (2) makes it less obvious what's changed in the list and (3) those default values change sometimes.

In any case, I will try to make it more obvious 👍

**Comment by 4DA** [comment]
That URL list is empty by default, so, I guess, ipfs daemon uses default values. If you put smotheing there it *stops using default values* and uses whatever you put there. So URL list *must* localhost:5001 etc.
