### ISSUE TITLE
PWA improvements, native version & ability to use specific version

### ISSUE THREAD

**Issue by icidasset** [icidasset/diffuse#273]
The app should be installable as a PWA already, and offline available. I want to move away from the native version, because (a) it's ineffecient, 100+ MB download, and (b) I can't build the linux and windows versions anymore.

To do:
- [x] Make sure the PWA is working properly
- [x] Explore https://web.dev/web-bundles/ & https://github.com/WICG/webpackage
- [x] Give https://github.com/tauri-apps/tauri-action another shot (see Github action)
- [x] ~~Try out https://wails.app/~~
- [x] ~~Figure out how to make the app "upgradeable", so people can stick with a specific version~~
       (Download a specific release from Github and host it yourself)

**Comment by Netherquark** [comment]
I am happy to report the PWA is working perfectly offline
only thing I noticed is that a different (I think default) wallpaper loads instead of the selected one when Diffuse is opened offline
Also, after the following sequence, Diffuse takes a lot of time to open:

- Open Diffuse offline
- Close Diffuse
- Restore Internet
- Open Diffuse with internet working

**Comment by icidasset** [comment]
@Netherquark Nice, thanks for testing that! 🙏 

I do have to rewrite the service worker so it uses the cached app files and fetches the new ones in the background (when online), instead of always fetching the new files. Will do this soon.

**Comment by icidasset** [comment]
- PWA is working fine
- Tried making a native build with https://tauri.studio
  But it doesn't work because Safari doesn't allow running service workers while using a custom protocol (ie. `tauri://`)
  Everything is in place thought, `src-tauri` and the Github action.
  Maybe this'll get fixed eventually.

**Comment by Netherquark** [comment]
[This](https://photos.app.goo.gl/cpxMjCxEbBvDBvad7) is still happening on android so I don't think the no tracks issue is rectified yet.

**Comment by icidasset** [comment]
Thanks @Netherquark I'll delve into more specific issues later.
