### ISSUE TITLE
Dropbox support Android

### ISSUE THREAD

**Issue by N214** [icidasset/diffuse#274]
The Dropbox support works fine on Desktop but not on mobile (Android)
Got an Error 400 Invalid redirect_uri.

**Comment by icidasset** [comment]
Thanks for creating an issue @N214 !
Does it say what the invalid redirect_uri is?
That'd be super helpful 🙏

**Comment by N214** [comment]
I just have the following screenshot, not sure what it is. 

![Screenshot_20210315-151234__01](https://user-images.githubusercontent.com/34739662/111167236-dc94bf80-85db-11eb-8f21-4568b83993a0.jpg)

Thanks for this project, I always wanted a solution like this, it's really awesome fellow belgian friend :)

**Comment by icidasset** [comment]
Glad to hear ☺️ 🇧🇪 Thank you for the screenshot! I'll look into it soon.

**Comment by icidasset** [comment]
Finally had a chance to look at this. You need to be on HTTPS, not HTTP. Dropbox does not support HTTP redirect URIs. The new beta version redirects to HTTPS automatically.

Let me know if that fixes it for you @N214

**Comment by N214** [comment]
Ah perfect, thank you ! Have a good long weekend ! @icidasset
