### ISSUE TITLE
Custom scrollbar

### ISSUE THREAD

**Issue by icidasset** [icidasset/diffuse#288]
Maybe we can remove that ugly scrollbar on windows that way 👀

**Comment by Netherquark** [comment]
afaik windows 11 is debuting an apple esque scrollbar. so this might not be as necessary? i cant find any preview screenshots and i cannot access my windows 11 pc right now but if my memory serves me right windows 11 beta insider has the new scrollbar. regardless, microsoft is planning to support win 10 till 2025 so this might still be a good idea.

**Comment by icidasset** [comment]
Oh that'd be great, thanks for the heads up @Netherquark

**Comment by Netherquark** [comment]
What's the status quo on this one? Seems like on Firefox on Linux, there is a macOS like scrollbar, so only windows is the problem. Considering that most people arent upgrading to 11, this might be worth it if you can dedicate the time to develop it. Your call.

**Comment by icidasset** [comment]
Not worth the effort since Windows 11 has the better looking scrollbar 👍
