### ISSUE TITLE
How to use with Azure [Question]

### ISSUE THREAD

**Issue by autr** [icidasset/diffuse#292]
Hello, looking to set up a file store with Azure - I've created file share with the correct CORS settings. Now what I'm looking for is the correct URL to use with the login. So for example, I have a file:

```
https://autr.file.core.windows.net/music/FTSE100.mp3
```

So my first assumption is:

```
autr@autr.file.core.windows.net
# or 
autr@file.core.windows.net
# etc
```

To log in. But I get:

```
400 The value for one of the HTTP headers is not in the correct format.
```

And generally I see no other form of URL to use, and a string `.well-known/webfinger?resource=autr`, which is something related to APFS?

**Comment by icidasset** [comment]
Hey :wave:

Not entirely sure what you're trying to do here.
What do you mean by "to use with the login"?
Diffuse doesn't let you "log in" with Azure, so I'm a bit confused 😅 

To use Azure with Diffuse you:
1. Log in using one of the provided options (simplest = My Browser)
2. Add a source
3. Choose 'Azure File Storage'
4. File in details (account key = access key)
5. Add source and wait for it to process

**Comment by autr** [comment]
Ahh thank you, I totally misunderstood how this works 😅

Grabbed the app and working perfectly, thank you!
