### ISSUE TITLE
User Layer errors via diffuse.sh

### ISSUE THREAD

**Issue by autr** [icidasset/diffuse#293]
Hello, I'm getting a console error after trying to authorise with a passphrase with a 5apps.com remote storage instance, which will then hang on the ajax spinner - and no error if continuing unencrypted / without passphrase:

```
brain.js:29 Uncaught TypeError: Cannot read property 'importKey' of undefined
    at brain.js:29
    at Array.<anonymous> (brain.js:29)
    at Function.f (brain.elm.js:1)
    at s (brain.elm.js:1)
    at Object.b (brain.elm.js:1)
    at Jr (brain.elm.js:1)
    at zr (brain.elm.js:1)
    at Wr (brain.elm.js:1)
    at bn (brain.elm.js:1)
    at sn (brain.elm.js:1)

```

Thanks!

**Comment by autr** [comment]
Also testing out other user layer login options and on Blockstack getting:

```
Failed to fetch information about the app requesting authentication. Please contact the app maintainer to resolve the issue.
```

And on Dropbox:

```
Invalid redirect_uri. It must exactly match one of the redirect URIs you've pre-configured for your app (including the path).
```

:-O

**Comment by icidasset** [comment]
Thanks for testing! Weirdly enough I don't have these issues.
What browser are you using? And incognito/private or regular?
Is this on https://diffuse.sh? HTTPS protocol?

I've not tested Blockstack though, that's getting removed.
There's a newer version, if you'd like to try that out:
https://nightly.diffuse.sh/

I really need to make a stable release soon 😅

**Comment by autr** [comment]
> Thanks for testing! Weirdly enough I don't have these issues.
> What browser are you using? And incognito/private or regular?
> Is this on https://diffuse.sh? HTTPS protocol?

Ah silly me - I forgot I was using Brave, and had "shields" up, so turning that off and Remote Storage is now working!

Both via https://diffuse.sh, with Dropbox (and deprecated Blockstack) error still there for Safari 13.1.2 and Chromium 92.0.4515.159, OSX

> I've not tested Blockstack though, that's getting removed.
> There's a newer version, if you'd like to try that out:
> https://nightly.diffuse.sh/
> 
> I really need to make a new stable release soon 😅

Yes please!

**Comment by icidasset** [comment]
Oh gotcha 👍  Sounds like I'll have to do some testing with Brave then.
Dropbox should work, on the error page, does it say where it's trying to redirect to?
That'd be really helpful 🙏

**Comment by autr** [comment]
Yep! Via console I can see the 400ing URL is `https://www.dropbox.com/oauth2/authorize?response_type=token&client_id=XXXXXXX&redirect_uri=http%3A%2F%2Fdiffuse.sh%2F%3Faction%3Dauthenticate%2Fdropbox` / `http://diffuse.sh/?action=authenticate/dropbox`

**Comment by icidasset** [comment]
Ah, that's because you're on the HTTP protocol instead of HTTPS.
Dropbox won't let us redirect to a "non-secure" url.

In the newer version it redirects automatically.
Although I though I had that in the current version as well 🤔 
I'll take a look at that, thanks again!
