### ISSUE TITLE
Music from the Apple Music Store no longer includes album art

### ISSUE THREAD

**Issue by icidasset** [icidasset/diffuse#296]
Until a half a year ago, or maybe longer, it used to be included in the metadata. It might be possible to use Apple's APIs to look for album art: https://bendodson.com/projects/itunes-artwork-finder/

https://github.com/public-apis/public-apis#music

**Comment by icidasset** [comment]
Apparently it's a bug in the Apple Music app? 🤔 

This script seems to fix the files:
https://dougscripts.com/itunes/scripts/ss.php?sp=mxapplyembeddedartwork

Not going to use the Apple API, needs a paid account.

**Comment by icidasset** [comment]
https://github.com/regosen/get_cover_art

**Comment by Netherquark** [comment]
I think this project is pretty cool, but as a backup, MusicBrainz could also be an alternative
