### ISSUE TITLE
Google Drive - Shared Drive Files cannot be scanned

### ISSUE THREAD

**Issue by akhil-rana** [icidasset/diffuse#299]
I've all my music in shared drive. 
I've tried implicitly passing folderId too when adding source but no luck.

**Comment by Rednaxela5** [comment]
> I've all my music in shared drive. I've tried implicitly passing folderId too when adding source but no luck.
I am experiencing the same issue. It can't detect the folders on my team shared drive.

**Comment by icidasset** [comment]
Hey folks, thanks for reporting this!
I tested the following scenarios.

Works:
- Scan everything, no folder id, does include everything from 'shared with me'
- Folder id, folder on my drive, id from url (eg. `1ZjBWuNeq7Tjg5358wIQ41P_Lb90OaGT7`)
- Folder id, folder in shared with me, id from url

Not possible:
- Only scan 'shared with me'
- Using shortcuts (need to look into this)

---

So that seems to work for me. I tried both regular and team accounts (at least I think it's a team account not a 100% on that). Also shares from both personal and team accounts (that is, team → personal account share, not other way around). I'm not sure what's different for you. Any thoughts?

Maybe it's an other issue altogether?
Could you tell me which browser you're using?
And if you see any errors in the developer console?

**Comment by icidasset** [comment]
<img width="869" alt="Screenshot 2021-12-11 at 17 32 21" src="https://user-images.githubusercontent.com/296665/145684266-50d60eb0-ce2b-414a-8e8c-9e03c63edf50.png">

Also, if possible, could you check this in the developer console?
If you're using a chromium based browser that is.
Check if the service worker is up to date, click the update button, or unregistered and reload page.
Timestamp should be recent (I circled this in red here).

**Comment by akhil-rana** [comment]
Thanks for looking into this.
I'm using a team share on personal account.
And 1st and 3rd point in your "works" section doesn't work for me as I've tried them. 
I used the public instance on diffuse.sh. Tried with custom api keys too. 
I've a folder named "songs" inside my shared drive. In which I've a collection of flac, mp3 files. 

I'm also not sure what's different for you. I'll try once again today and let you know.

Also if there's anything else you might need to investigate this then do let me know.

**Comment by akhil-rana** [comment]
> Hey folks, thanks for reporting this! I tested the following scenarios.
> 
> Works:
> 
> * Scan everything, no folder id, does include everything from 'shared with me'
> * Folder id, folder on my drive, id from url (eg. `1ZjBWuNeq7Tjg5358wIQ41P_Lb90OaGT7`)
> * Folder id, folder in shared with me, id from url
> 
> Not possible:
> 
> * Only scan 'shared with me'
> * Using shortcuts (need to look into this)
> 
> So that seems to work for me. I tried both regular and team accounts (at least I think it's a team account not a 100% on that). Also shares from both personal and team accounts (that is, team → personal account share, not other way around). I'm not sure what's different for you. Any thoughts?
> 
> Maybe it's an other issue altogether? Could you tell me which browser you're using? And if you see any errors in the developer console?

I'm using brave browser on latest build. Will inform of any console errors if there soon.

Also I would like to point out that "shared with me" is different from "shared drives" as I understand. They are also knows as "team drives" I think. I've attached a screenshot of my drive showing "shared with me" and "shared drives" separately for better understanding.


![Screenshot_20211211-221315129~3](https://user-images.githubusercontent.com/36575628/145684774-29ccb4e9-d160-4356-82cd-f58f3a6f1d75.jpg)

**Comment by akhil-rana** [comment]
> Also, if possible, could you check this in the developer console?
If you're using a chromium based browser that is.
Check if the service worker is up to date, click the update button, or unregistered and reload page.
Timestamp should be recent (I circled this in red here).

No errors in console.
And service worker timestamp is also recent.

**Comment by icidasset** [comment]
@akhil-rana Thanks! Ah you're right, "shared drives" are something different, I didn't know these existed 😅

Fixed in v3.0.1
https://github.com/icidasset/diffuse/releases/tag/3.0.1

**Comment by icidasset** [comment]
Forgot to mention this, if you're using https://diffuse.sh and want to make sure you're running version `3.0.1`. You can go to this section in the dev console and click this link:
<img width="499" alt="Screenshot 2021-12-13 at 18 20 21" src="https://user-images.githubusercontent.com/296665/145858934-6af36c89-d203-4669-89b5-a8918d1a049f.png">

It should show the version there.

<img width="447" alt="Screenshot 2021-12-13 at 18 22 53" src="https://user-images.githubusercontent.com/296665/145859120-0dd41b9a-29b4-45c9-9345-d5f99e0eb24e.png">

Usually it takes a while, or a few refreshes, for the service worker to update.

**Comment by Rednaxela5** [comment]
> Forgot to mention this, if you're using https://diffuse.sh and want to make sure you're running version `3.0.1`. You can go to this section in the dev console and click this link: <img alt="Screenshot 2021-12-13 at 18 20 21" width="499" src="https://user-images.githubusercontent.com/296665/145858934-6af36c89-d203-4669-89b5-a8918d1a049f.png">
> 
> It should show the version there.
> 
> <img alt="Screenshot 2021-12-13 at 18 22 53" width="447" src="https://user-images.githubusercontent.com/296665/145859120-0dd41b9a-29b4-45c9-9345-d5f99e0eb24e.png">
> 
> Usually it takes a while, or a few refreshes, for the service worker to update.

Thank you for the quick response. It can now detect the songs in my shared drive.

**Comment by akhil-rana** [comment]
Thank you for looking into this and implementing quickly.
Files are now detected as expected.
