### ISSUE TITLE
Artist view and album view should function like playlists, setting the artist/album in view as the pool to play the next song from as is the case with playlists

### ISSUE THREAD

**Issue by icidasset** [icidasset/diffuse#305]
Will be configurable in settings, on by default.

**Comment by icidasset** [comment]
@Netherquark I know you've wanted this one for a long time, it's finally here 😜 Let me know if you find any quirks, haven't tested it extensively yet, but it is on nightly.

**Comment by Netherquark** [comment]
did a bit of testing, seems to be working essentially perfectly! Awesome work!
