### ISSUE TITLE
Improve key bindings

### ISSUE THREAD

**Issue by icidasset** [icidasset/diffuse#306]
> Alt + (1/2/3/4/5/6/7/8/9) can be used in Firefox to cycle through tabs. Say diffuse is the first tab I have open, and I want to go to the second tab. I'll press alt+2. But, diffuse also picks up the "2" keypress, and opens the playlist pane accordingly. Also happens with alt 1,3,4,8,9

> Maybe it would be better if the shortcuts for previous/next song are [ and ] along with { and } and the shortcuts to seek are , and . along with < and > because on a standard QWERTY keyboard, curly and angled brackets are secondary inputs, preceded by square brackets, and comma and period respectively.

> Currently, it is not possible to switch between the list and cover view using the keyboard.

> It is also not possible to toggle favourites-only using the keyboard.

**Comment by Netherquark** [comment]
on chrome on windows, using ctrl p does play/pause but it also opens the print dialogue

**Comment by icidasset** [comment]
> on chrome on windows, using ctrl p does play/pause but it also opens the print dialogue

Yeah, there's no perfect set of key bindings it seems like (differences between browsers, os, etc).
But generally for play and pause I'd use the media keys most keyboards have?

**Comment by Netherquark** [comment]
Yeah I use the media bindings anyways just thought there might be some way to bypass the pop up. Its alright either way i guess
