### ISSUE TITLE
Source slow listing

### ISSUE THREAD

**Issue by fadyanwar** [icidasset/diffuse#307]
After adding an IPFS source, it gets stuck on %5 for a very long time then suddenly shows up the album.

**Comment by icidasset** [comment]
👋 I could use a bit more information, such as:
1. What is the gateway? A public one, or just local? Don't need the exact details, but a bit more info would be helpful.
2. Was the content entirely cached on that gateway, or did it need to load certain parts from elsewhere?
3. When you remove the source after the initial processing, and then add it back, is the processing/listing faster?
4. How much data does the CID/hash represent?

**Comment by fadyanwar** [comment]
The CID folder size was 113 MB to be exact and is hosted over ipfs.io and is fully cached. Removing the source and adding it again did not help. Listing was stuck in %5 no matter what I do, i.e. reloading, refreshing and removing the source and adding it again.

**Comment by icidasset** [comment]
Sorry for the late response.
I'm not sure I can help much here, I'm guessing it's just ipfs.io being slow? 🤷 

Would be interesting to hear if you have the same issue if you use a local IPFS node.
True, local would be faster in any case, but if it were fully cached on ipfs.io, the difference shouldn't be that big.
