### ISSUE TITLE
Scrobbling fails on repeated tracks

### ISSUE THREAD

**Issue by lanced4dragons** [icidasset/diffuse#312]
ISSUE: When you loop a track, it doesn't track any scrobbles past the first run-through. (E.G. repeated listens don't show up). I think this could be because scrobbles are only counted when you press 'play' and not any other time, even when the track starts over again.

**Comment by icidasset** [comment]
I totally missed this one sorry.
That's indeed something I didn't implement, will change 👍

**Comment by icidasset** [comment]
@lanced4dragons Finally had some time to investigate. Diffuse v3.1.0 (not released yet) will tell Last.fm to scrobble the track again on repeat.
