### ISSUE TITLE
Feature Request: See folders, make playlist with folder

### ISSUE THREAD

**Issue by ajarang** [icidasset/diffuse#321]
This is an insanely cool little app- thank you for making it. Some suggestions:
- View folders from the Cloud Drive: My music in google drive is sorted by genre. It would be nice to...
- Add to queue/playlist from folder

**Comment by Netherquark** [comment]
Are you referring to directory playlists? Not sure if they work since I don't use them, but seems like if you go to sources>triple dot menu you can enable or disable directory playlists. they are enabled by default for me. maybe it no longer works. im sure icidasset can help out here, but just piping in to say the feature is "implemented"

**Comment by icidasset** [comment]
Thank you ☺️ 

What @Netherquark said basically (thanks for chiming in @Netherquark 🙏 )
I'm always using directory playlists, definitely still works.

How it works, if you have a `/Music/Genre/` folder on your Google Drive, and you've passed the `Music` folder id, then `Genre` will be a 'directory playlist'.

Could be interesting to add the option to add an entire playlist to the queue 🤔 It's easy to do, so I might add that. _(Note to self, could also be handy to "copy" a directory playlist to a normal playlist)_

Also useful: grouping by directory (via 3 dots menu next to search)

**Comment by ajarang** [comment]
Hmm, I think I see. I have multiple nested folders, and each album is within a folder, so It could be possible that the option is simply seeing the "low level" folders. With the option selected, I only see a list of albums, the same as before.

**Comment by icidasset** [comment]
Yes the "directory playlists" option is only for the first level of the folder path.
Given the following directory structure:
```
/dn'b . jungle/dBridge_and_Resolution_No_1-Libra__The_Bride-SINGLE-2003-BOUGHT/02-the_bride.m4a
/dn'b . jungle/adred-autofacs_(feat._jamal).m4a
```
This will give you 👇

_Playlists screen:_
<img width="891" alt="Screenshot 2022-02-25 at 15 46 38" src="https://user-images.githubusercontent.com/296665/155735160-d704a608-5207-4676-af4a-7a62b235920f.png">

_Tracks screen:_
<img width="895" alt="Screenshot 2022-02-25 at 15 45 10" src="https://user-images.githubusercontent.com/296665/155735048-7512de9b-1f20-49da-bc8c-19f4ade6fde1.png">

**Comment by icidasset** [comment]
It should be possible to:
- Convert a directory playlist to a regular playlist (note: regular playlist won't automatically update)
- Add an entire playlist to the queue (be it a directory or regular playlist)

**Comment by icidasset** [comment]
Implemented.
