### ISSUE TITLE
Fission authentication broken

### ISSUE THREAD

**Issue by jphastings** [icidasset/diffuse#324]
When choosing "Fission" as an authentication method I'm presented with an eternal spinner (and a JS error in the console):
<img width="1365" alt="diffuse-fission" src="https://user-images.githubusercontent.com/42999/166225211-7878b8ca-1bf2-48f3-9951-bf0ec91d5d1a.png">

I don't _think_ I'm doing anything wrong, but it does look like a there's an error in the JS (`self.IpfsMessagePortClient.from` is not a function) — please let me know if there's anything I can do to help in debugging!

**Comment by icidasset** [comment]
Thanks for creating the issue! You're indeed not doing anything wrong, it is broken 😉 Will try to fix soon.

**Comment by icidasset** [comment]
Fix will be in `3.1.0`
