### ISSUE TITLE
Desktop Diffuse does not detect some .flac songs in cloud Google Drive

### ISSUE THREAD

**Issue by Insidevk18** [icidasset/diffuse#335]
> Windows version : windows 10 Pro 21H2
> Diffuse desktop version : 3.0.2 (latest)
> Cloud service : Google drive (shared drive)
> music file format :  .flac

![image](https://user-images.githubusercontent.com/94028610/172295518-9bc88198-a0af-4821-9d2c-c4205678c726.png)

![image](https://user-images.githubusercontent.com/94028610/172295543-fa44127c-8c48-42e2-9768-5bf6d5219cc0.png)

I had it rescan my Google drive several times but the problem still persists.

My .flac music files are not corrupted or anything, I tried it on Foobar2000 and it plays normal.

**Comment by icidasset** [comment]
Hmm 🤔 When you switch to the list view, does it show the other tracks without the proper metadata (eg. like the filename as the track title)?

If possible, for debugging purposes, can you share the files with me? My email is: `icid.asset @ gmail . com`
Also, did you use a folder id?

**Comment by Insidevk18** [comment]
> Hmm 🤔 When you switch to the list view, does it show the other tracks without the proper metadata (eg. like the filename as the track title)?
> 
> If possible, for debugging purposes, can you share the files with me? My email is: `icid.asset @ gmail . com` Also, did you use a folder id?

_______________________________________________________________________________________________________________________________________

Hello "icidasset", thank you very much for addressing this problem, I switched to the list view and the problem still persists.

![image](https://user-images.githubusercontent.com/94028610/172530338-48209ee7-fff3-4c7a-91aa-be6008d078f4.png)

It is also not found in the "unknown" part, those files are other songs.

![image](https://user-images.githubusercontent.com/94028610/172530248-b2fa3db2-0e41-435d-b3fb-1fc4f9c61775.png)

> Also, did you use a folder id?


You mean how do I link my Google Drive cloud? I linked Diffuse to Google Drive NOT BY API KEY, I did it the simple way, linking my Mail with Diffuse and giving it permission to access my Google Drive files.

On the other hand, I also put a "security password" which is what they asked me for the first time to link Google Drive.

> If possible, for debugging purposes, can you share the files with me?

Of course, my friend, I already shared my folder with you, if you have any problem accessing my files, don't hesitate to tell me, I'll be able to find another way to send them to you :)

**Comment by icidasset** [comment]
> Of course, my friend, I already shared my folder with you

Thanks! ☺️ 

<img width="742" alt="Screenshot 2022-06-08 at 09 21 42" src="https://user-images.githubusercontent.com/296665/172556517-0809e317-2d37-45b6-8e5b-35dee22a48bd.png">

Looks like it works fine on my end 🤔 I think this might be another case of Google Drive's "API rate limit" (hence why I suggest using other types of sources). That is, Diffuse makes too many requests according to Google Drive, so Drive blocks them, resulting in missing files or missing metadata (hence the "unknown" artist + title). You can double check if that's the case by opening the browser console (aka. developer tools), while processing, and looking for error messages.

Although... that doesn't explain why the missing tracks don't show up when processing again, unless they were imported without the metadata (ie. "unknown" artist + title). Are there no other tracks missing, besides from that album?

Another few things you can try:
- Adding that folder specifically to Diffuse by adding another 'Google Drive' source with the folder id of that folder (see below for folder id info)
- Exporting your Diffuse data via 'Settings' and looking for the missing tracks in that json file. Normally they shouldn't be in there, but can't hurt to double check.

> You mean how do I link my Google Drive cloud?

I meant this form field when adding a source:
<img width="374" alt="Screenshot 2022-06-08 at 10 11 30" src="https://user-images.githubusercontent.com/296665/172566509-bc84b1ed-98cc-436b-93e4-2628a31817af.png">

The folder id is this part of the url:
<img width="454" alt="Screenshot 2022-06-08 at 10 37 48" src="https://user-images.githubusercontent.com/296665/172572167-c6308d50-7e3f-47bd-aa5a-474eedd115d8.png">

**Comment by Insidevk18** [comment]
Hello "icidasset"
Hmm, apparently it is because having too many songs did not successfully scan all of them?
In fact there are 2 albums that load me the songs but without the metadata, and one of them is a .flac album that lasts approximately 50 minutes (all the compact album in a single .flac file) and loads it without metadata and as " unknown", but since I could still hear it in the part of unknown songs I didn't care.

> Are there no other tracks missing, besides from that album?

Yes, I have a Linkin park album that is a 32-bit 192 khz .flac file, it doesn't scan the album at all, and something similar happens to me when I load an album that was .wav

> Another few things you can try: Adding that folder specifically to Diffuse by adding another 'Google Drive' source with the folder id of that folder (see below for folder id info)

It worked, but it wasn't at the start, I had to skip my first source to find the full album :)
![image](https://user-images.githubusercontent.com/94028610/172785229-6803a54f-f17c-4dcc-b0f6-cbcdda692ef9.png)
![image](https://user-images.githubusercontent.com/94028610/172785280-9d32bab5-2f5e-40df-af0e-4b3807fd8b0c.png)
![image](https://user-images.githubusercontent.com/94028610/172785334-6fb7de2a-c177-4556-8956-ec35d69a8d6e.png)

I think that with this method I will be able to listen to the albums that are not processed at first :)

**Comment by icidasset** [comment]
Thanks for testing so thoroughly and all the info! 

> It worked, but it wasn't at the start, I had to skip my first source to find the full album

Interesting.. Glad that worked! Somewhat at least 😅 

> Hmm, apparently it is because having too many songs did not successfully scan all of them?

Kind of, if you were to use any other type of source with Diffuse, you'd have much better results. For example, I have 13000 tracks on Amazon S3, and that scans just fine (although it takes a long time if you scan it all at once). Because of the Google Drive API rate limiting, there's a limit to what you can scan, and I think because flac files are so large the API has extra trouble going through all of it 🤷‍♂️

Sidenote: If anyone needs help using other types of sources in Diffuse, let me know. I'm writing some small guides on how to use them: https://github.com/icidasset/diffuse/discussions

At some point I'm going to take another stab at improving the performance/stability of all of this Google Drive stuff, but I don't have a lot of time to work on this project. You can track that at #338 if you want to.

Sorry I can't help more 😥

**Comment by Insidevk18** [comment]
> Thanks for testing so thoroughly and all the info!
> 
> > It worked, but it wasn't at the start, I had to skip my first source to find the full album
> 
> Interesting.. Glad that worked! Somewhat at least 😅
> 
> > Hmm, apparently it is because having too many songs did not successfully scan all of them?
> 
> Kind of, if you were to use any other type of source with Diffuse, you'd have much better results. For example, I have 13000 tracks on Amazon S3, and that scans just fine (although it takes a long time if you scan it all at once). Because of the Google Drive API rate limiting, there's a limit to what you can scan, and I think because flac files are so large the API has extra trouble going through all of it 🤷‍♂️
> 
> Sidenote: If anyone needs help using other types of sources in Diffuse, let me know. I'm writing some small guides on how to use them: https://github.com/icidasset/diffuse/discussions
> 
> At some point I'm going to take another stab at improving the performance/stability of all of this Google Drive stuff, but I don't have a lot of time to work on this project. You can track that at #338 if you want to.
> 
> Sorry I can't help more 😥

_______________________________________________________________________________________________________________________________________

Don't worry friend, you helped me enough, being able to enjoy my music from the cloud for free is enough for me, thanks for the project :)
