### ISSUE TITLE
Unable to uninstall from Control Panel in Windows 10

### ISSUE THREAD

**Issue by Centribo** [icidasset/diffuse#340]
Currently on Windows 10, Version 10.0.19043 Build 19043 with Diffuse v3.1.0.

Was trying to uninstall Diffuse by going to the control panel. First is that the install is listed as "Diffuse 3.0.2" though I can verify that v3.1.0 is the installed version. When I try to uninstall, the uninstaller tells me that Diffuse is running, and it will try to close it before uninstalling. Trying to proceed, it can't close it so it doesn't proceed with the uninstall and keeps telling me to close Diffuse. I've verified with Task Manager, `tasklist` in CMD, and `get-process` in powershell that no "Diffuse" process is running

![Un_A_2022-06-27_11-39-19](https://user-images.githubusercontent.com/6460973/175979191-25c8d7a7-3c4e-45bf-a8ae-19fd1ad177a9.png)
![Un_A_2022-06-27_11-39-08](https://user-images.githubusercontent.com/6460973/175979195-000ca762-6715-47eb-a99f-6e0643fd38f9.png)
.

**Comment by icidasset** [comment]
Thanks! Seems to be a https://github.com/electron-userland/electron-builder issue, which I use to make "native" builds. More info here: https://github.com/electron-userland/electron-builder/issues/6916 (see last comment)

Seems like I have to upgrade, will do so for next release 👍 

PS. "Native" build code is at https://github.com/icidasset/diffuse-native in case anyone is looking for that.

**Comment by icidasset** [comment]
I made a pre-release with the new builds: https://github.com/icidasset/diffuse/releases/tag/3.2.0-pre.1
Let me know if that works for you.
It's now an `.msi` file instead of `.exe`

**Comment by Centribo** [comment]
Can confirm the 3.2.0 installer correctly uninstalls on Windows 10, though the installation doesn't seem to install "over"/replace the older version, and it's listed as a separate installation in the Control Panel. Control panel shows both Diffuse 3.2.0 and Diffuse 3.0.2.

**Comment by icidasset** [comment]
Thanks for testing! Yeah the separate installation is expected, it's a totally different build system I'm using. It's all automatically generated, so not much I can do there. Will close once 3.2.0 is released.

**Comment by Netherquark** [comment]
chiming in here to say, if you still want to get rid of the old installation and its generated files, you could try using Revo uninstaller or some equivalent. but I doubt creating an uninstaller for the old version which is using the old build system is in the current scope of the project.
