### ISSUE TITLE
Host diffuse on IPFS

### ISSUE THREAD

**Issue by Winterhuman** [icidasset/diffuse#341]
Diffuse is a static application, and it has support for IPFS within itself, but, to use it on the web you either need to selfhost it or go to https://diffuse.sh. What about hosting diffuse on IPFS and linking the resulting CID here? (Or, maybe consider Cloudflare's support for DNSLink so you could make https://diffuse.sh point to a CID/IPNS address)

Please say if this isn't trivial to implement given the current hosting setup.

**Comment by icidasset** [comment]
Hey 👋  Diffuse is actually hosted on IPFS, it's hosted on the gateway from https://fission.codes and routed through Cloudflare.

So, diffuse.sh has this DNSLink `dnslink=/ipns/diffuse.fission.app`
and thus redirects to `dnslink=/ipfs/bafybeidn5idk7u54lcg3ngtm52upbywldyklimpdykeabb3kc6qrnytnni`

See https://dnsrecords.io/_dnslink.diffuse.sh and https://dnsrecords.io/_dnslink.diffuse.fission.app

**Comment by Winterhuman** [comment]
Oh sweet, I never realised. Is there a reason https://diffuse.fission.app isn't mentioned anywhere?
