### ISSUE TITLE
iOS Compatibility 

### ISSUE THREAD

**Issue by ChummyX** [icidasset/diffuse#346]
I am running iOS 15.5, and using the latest version of the diffuse website nightly.diffuse.sh. It work marvelously on my computer, but on my iPhone 13 it will display the interface perfectly, catch is play button doesn't work and can never get tracks to start. I've tried it on Safari, Google, Opera GX, DuckDuckGo, and Chrome. All acted exactly the same way. I am not sure what is causing this or how to troubleshoot. All of my files are FLAC, accessed via Google Drive.

**Comment by icidasset** [comment]
Seems to be an issue with Google Drive, the other sources work. I'll look into it. Thanks for creating an issue!

**Comment by ChummyX** [comment]
Considering purchasing an alternative option for mobile, wanted to check first if there was an estimated timeline on a fix just in case. No pressure at all, just curious where it's at :)

**Comment by icidasset** [comment]
Issue should be resolved now on `nightly.diffuse.sh`, check for update on settings screen. Still don't really understand why Safari is acting so weird compared to other browsers, but it mostly works now 🤷‍♂️ (all browsers are still using the mobile-safari browser engine underneath on iOS)

Will close issue once stable version has released.
