### ISSUE TITLE
 "diffuse-windows.exe" is broken (Does not install Diffuse in windows 10 21H2)

### ISSUE THREAD

**Issue by Insidevk18** [icidasset/diffuse#348]
Good morning, I open this thread to report a bug in the Diffuse installer package regarding Windows.
-Windows version: Windows 10 21H2
_Diffuse version: v3.1.1
![image](https://user-images.githubusercontent.com/94028610/183306945-c8e4633e-7954-4b66-8e1f-b8c2a3144e90.png)

I get a message that says: "The item "Diffuse.exe" referenced by this shortcut was changed or moved, so the shortcut will not work properly. Do you want to remove this shortcut?"
![image](https://user-images.githubusercontent.com/94028610/183307019-70200fbc-c5f8-4754-8533-7348a435b902.png)

Look for diffuse in the various folders created.
![image](https://user-images.githubusercontent.com/94028610/183307051-34e5a8fe-77b7-4111-ad0b-aee13b14fd59.png)
![image](https://user-images.githubusercontent.com/94028610/183307055-f2c27fed-0795-4d10-a6e0-0d4fb85f3325.png)

I installed through that access, but only got the same result.
![image](https://user-images.githubusercontent.com/94028610/183307078-4341d2bc-74d1-46d1-aba3-6294482b9725.png)

Thanks.

**Comment by icidasset** [comment]
Thanks for creating the issue! I'm currently working on new (native) binaries, will be fixed in the next release.

**Comment by icidasset** [comment]
I made a pre-release with the new builds: https://github.com/icidasset/diffuse/releases/tag/3.2.0-pre.1
Let me know if that works for you.
It's now an `.msi` file instead of `.exe`

**Comment by Insidevk18** [comment]
> Hice un prelanzamiento con las nuevas versiones.: https://github.com/icidasset/diffuse/releases/tag/3.2.0-pre.1 Déjame saber si eso funciona para ti. ahora es un `.msi` archivo en lugar de `.exe`


Good morning, this version of Diffuse does install, only when I wanted to integrate it into my google drive account, I couldn't even get the client ID, I guess it might be because it was a pre-launch.

![image](https://user-images.githubusercontent.com/94028610/183986785-4c940a7e-e984-4099-8a15-81827e841f40.png)

**Comment by icidasset** [comment]
You mean this screen?

<img width="530" alt="Screenshot 2022-08-13 at 15 07 48" src="https://user-images.githubusercontent.com/296665/184495558-1a0b7019-6299-46ff-902b-7619d110e0cd.png">

That should now be fixed, I forgot to configure something in the Google Client, no need to download new version of Diffuse.

**Comment by Insidevk18** [comment]
> Eso ahora debería arreglarse, olvidé configurar algo en el cliente de Google, no es necesario descargar una nueva versión de Diffuse.

Yes, I got a screen, apparently that problem was solved but another one arose.
![image](https://user-images.githubusercontent.com/94028610/184521624-e9bc33c9-18ee-44f6-995c-728ca74cc533.png)
It appears to me that: "Could not log in" It is possible that the browser or the application is not secure. Try another browser. If you are already using a supported browser, you can try signing in again.
Apparently this problem arises because google no longer allows "Access pps less secure", it is no longer available to enable it in google, I have also had this problem in the "Ferdium" github project, maybe it is due to electron?
![image](https://user-images.githubusercontent.com/94028610/184521706-19e7d4f6-16c0-42fc-9a71-d69e6b64e890.png)

**Comment by icidasset** [comment]
Hmm, didn't think Google would be so annoying. Anyhow, there's a few ways around this, I described everything here: https://github.com/icidasset/diffuse/issues/351 Thanks again for testing!

**Comment by icidasset** [comment]
@Insidevk18 Should be fixed in [v3.2.0-pre.2](https://github.com/icidasset/diffuse/releases/tag/3.2.0-pre.2)

Will close issue once stable version is out.
