### ISSUE TITLE
PWA on iOS sometimes loads forever

### ISSUE THREAD

**Issue by icidasset** [icidasset/diffuse#360]
Not sure what’s going on, maybe something to do with auth 🤷‍♂️

---

I had this using the Dropbox auth method, when already logged in previously.

Ruled out:
- [x] Missing secret key, it shows an error message if that's the case.

**Comment by Netherquark** [comment]
usually this happens to me with the wrong decryption key for the user layer, or if I have a spotty internet connection. Might be something totally different since this is iOS and safari, but my 2c

**Comment by icidasset** [comment]
Thanks for the insights @Netherquark I think you're on the right track there.

**Comment by icidasset** [comment]
Most likely been fixed by #372 Will reopen in case it's not.

**Comment by Netherquark** [comment]
I dont have my old iPad mini anymore, so cant test.
