### ISSUE TITLE
First impressions and minor issues

### ISSUE THREAD

**Issue by jcmrva** [icidasset/diffuse#363]
I've been meaning to try this since I saw it on a "cool Elm apps" post a while back. The release notice prompted me to finally set up some music for it. Very cool! This will be a good alternative to finding tracks on YT @ work.

Some observations, mostly:

Firefox appears to be supported but it spins indefinitely at this point. No console errors.
![diffuse-ff-noload](https://user-images.githubusercontent.com/20140997/192162444-3f6b9690-75b2-4a43-baed-c28ad64af3b0.png)

Lots of music players are more forgiving about broken/missing metadata, so I didn't notice some of my files had issues until I uploaded them. Then I found that fixing them (via Azure blob service) is a bit tedious: delete the file, process the source to get it out of the app, upload the fixed file, process again.

The Ctrl + _ shortcuts work but also perform browswer functions. I see there was an issue about this - mentioning it again just in case.
- K focuses the browser URL bar.
- 1-x switches browser tabs.

The volume slider doesn't appear on the album view.

I like the track highlight changing along with the background, but that can result in low contrast depending on the image.
![diffuse-nowplaying-contrast](https://user-images.githubusercontent.com/20140997/192162463-f1bb03f2-c596-49ba-9275-570d86558227.png)

If an artist has multiple albums (with covers), it would be nice if the artist view had a collage of some kind, e.g.
![image](https://user-images.githubusercontent.com/20140997/192162583-7755032b-5b18-4809-ad32-b846f54d97a4.png)

Good job handling super long track titles and special characters - I haven't found anything that breaks it yet. 😁 
![image](https://user-images.githubusercontent.com/20140997/192163804-35805f17-1afe-405c-8cfe-99d1ebb48038.png)

Noticed [this comment](https://github.com/icidasset/diffuse/issues/118#issuecomment-403319847) - what happens when we exceed 1000 items?

**Comment by icidasset** [comment]
Hi, thank you for all the feedback! ☺️ 

> Firefox appears to be supported but it spins indefinitely at this point. No console errors.

This is most likely because it's downloading all the application files and all the background images (25MB total) in the background so that the application works offline (done through service worker). Sometimes it takes a while, especially if the server is slow to respond. Does it still happen when you refresh?

> Then I found that fixing them (via Azure blob service) is a bit tedious: delete the file, process the source to get it out of the app, upload the fixed file, process again.

There's a shortcut for this. If you hold the OPTION (I think that's ALT on non-Mac devices) and right-click on a track, you should get the option to "sync tags". 

> The Ctrl + _ shortcuts work but also perform browswer functions

Not sure if I can do anything about that. Suggestions are welcome!

> The volume slider doesn't appear on the album view.

Oh that's new, it should be there. Can you send me a screenshot? And device + browser info 🙏 

> can result in low contrast depending on the image.

Need to create an issue for this 👀 

>  it would be nice if the artist view had a collage of some kind, e.g.

Could be cool yeah, good suggestion 👍 

>  I haven't found anything that breaks it yet.

🎉 

> what happens when we exceed 1000 items?

What happens is what is described in the issue. Too much data for the code to process at once or something like that, hard to tell exactly.

**Comment by jcmrva** [comment]
> > Firefox appears to be supported but it spins indefinitely at this point. No console errors.
> 
> This is most likely because it's downloading all the application files and all the background images (25MB total) in the background so that the application works offline (done through service worker). Sometimes it takes a while, especially if the server is slow to respond. Does it still happen when you refresh?

I let it sit for ~5 minutes and figured that was enough. Not sure what the issue was but it's working on FF on my other machine now at least.

> > The volume slider doesn't appear on the album view.
> 
> Oh that's new, it should be there. Can you send me a screenshot? And device + browser info 🙏

![image](https://user-images.githubusercontent.com/20140997/192385284-56f2a6f6-ae74-4f39-8a3d-4f74a1f7b9f2.png)
Not much to see... I click and nothing happens. Tried double-clicking just in case. Win 10, latest Firefox & Chrome.

> > what happens when we exceed 1000 items?
> 
> What happens is what is described in the issue. Too much data for the code to process at once or something like that, hard to tell exactly.

Sorry, I meant: does it make multiple requests or only get the first 1000?

**Comment by icidasset** [comment]
Thanks! I'll look into these issues.

> Sorry, I meant: does it make multiple requests or only get the first 1000?

Oh yeah definitely multiple requests, it's in batches of 1000.

**Comment by icidasset** [comment]
Tracking these issues in:
- https://github.com/icidasset/diffuse/issues/366
- https://github.com/icidasset/diffuse/issues/365
- Another app loads forever issue: https://github.com/icidasset/diffuse/issues/360
- https://github.com/icidasset/diffuse/issues/367
