### ISSUE TITLE
remoteStorage option does not sync

### ISSUE THREAD

**Issue by mscottnelson** [icidasset/diffuse#376]
When using remoteStorage option, the remoteStorage provider sends its response, but Diffuse simply drops the information, and no User data sync occurs.

**Comment by icidasset** [comment]
👋  I was just working on this. I think I broke it somewhere along the road, or something else changed 🤔 Which server are you using?

**Comment by icidasset** [comment]
The issue in my testing is that the access token is missing from the OAuth response, but I haven't figured out why that is.

**Comment by icidasset** [comment]
Ok found the issue, will be fixed in the next release.
Will close this once it's released.

**Comment by mscottnelson** [comment]
Fantastic, thanks for picking this up so quickly!

**Comment by icidasset** [comment]
Released stable version 3.3
https://github.com/icidasset/diffuse/releases/tag/3.3.0
