### ISSUE TITLE
Blank window launching the AppImage Ubuntu 22.10

### ISSUE THREAD

**Issue by logix2** [icidasset/diffuse#388]
When launching the AppImage binary (version 3.3.0) on Ubuntu 22.10, I get a blank window and the following terminal output:
```
./diffuse-linux-amd64.AppImage 
GStreamer element appsink not found. Please install it
GStreamer element autoaudiosink not found. Please install it

(WebKitWebProcess:64679): GLib-GObject-WARNING **: 20:42:29.500: invalid (NULL) pointer instance

(WebKitWebProcess:64679): GLib-GObject-CRITICAL **: 20:42:29.500: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```
The DEB package does work though

I believe [this tauri bug](https://github.com/tauri-apps/tauri/issues/4642) might be related: "_tauri.bundle.appimage.bundleMediaFramework works only when building on ubuntu for now. I wanted to "fix" this for weeks now, but couldn't find the time to do it yet..._".

**Comment by icidasset** [comment]
Thanks for creating an issue! I really should test on Linux at some point 🙈

**Comment by icidasset** [comment]
I will no longer be maintaining the native wrapper app.
More context here: https://github.com/icidasset/diffuse/blob/main/CHANGELOG.md#340
