### ISSUE TITLE
Almost unreadable text under Linux using the native build

### ISSUE THREAD

**Issue by logix2** [icidasset/diffuse#389]
Using the native app, the text is almost unreadable on Linux. Tested version 3.3.0 under Ubuntu 22.10 and Manjaro Linux. Screenshot:

![Screenshot from 2023-03-08 21-48-12](https://user-images.githubusercontent.com/38005360/223829957-45602052-b7e0-4f2b-a8cc-cf6d56bf5169.png)

I'm using a standard 1920x1080 resolution with the default DPI.

**Comment by icidasset** [comment]
I will no longer be maintaining the native wrapper app.
But just in case, this isn't happening in the browser is it?

**Comment by icidasset** [comment]
Sorry for the noise, tracking in #409 instead.
