### ISSUE TITLE
Alternative sponsor methods

### ISSUE THREAD

**Issue by multikatt** [icidasset/diffuse#397]
I think this project is really great but I dislike Github's sponsorship. Would you mind setting up alternative methods, preferably crypto methods or patreon?

**Comment by icidasset** [comment]
Thanks @multikatt ! For sure.

Here's my patreon:
https://patreon.com/diffuse

(has some polls, in case you want to give some feedback)

And ko-fi:
https://ko-fi.com/icidasset

**Comment by multikatt** [comment]
Great, thanks for setting this up!
