### ISSUE TITLE
Diffuse doesn't send authentication to apache webdav server after PROPFIND

### ISSUE THREAD

**Issue by ST-Saint** [icidasset/diffuse#399]
OS: Archlinux
Kernel: 6.4.1
Arch: amd64
Apache version: 2.4.57
Diffuse version: 0.8.2

AuthType: Digest

CORS config
```conf
  Header always set Access-Control-Allow-Origin *
  Header always set Access-Control-Allow-Headers *
  Header always set Access-Control-Expose-Headers *
  Header always set Access-Control-Allow-Methods *
```

Wireshark log: (diffuse auth + cadaver auth)
[wireshark.zip](https://github.com/icidasset/diffuse/files/12779308/wireshark.zip)

**Comment by icidasset** [comment]
Thanks for creating an issue! Not entirely sure I'm reading these logs correctly, but it seems like your Apache WebDAV server is requiring authorisation on `OPTION` requests. This is something web browser don't support, see https://stackoverflow.com/a/52072116 for more info on that.

Is that the case? Or did I misinterpret the logs? Also just to be sure, check if the service worker is running or isn't bypassed.

**Comment by ST-Saint** [comment]
interesting... 
 I tried Firefox and Chrome, and both of them use `GET`. cadaver uses `OPTIONS` but also attaches authorization but diffuse cannot add authorization within the `OPTIONS` request. 

I thought since I have `Header always set Access-Control-Allow-Methods *`  it already allows `OPTIONS` without auth. Do you know what else have to configure to allow that?

**Comment by ST-Saint** [comment]
Thanks for the pointer, exempting OPTIONS allows diffuse to connect to WebDAV now

```xml
<Directory "/home/y/WebDAV/WebDAV">
  DAV On
  AllowOverride None
  Options Indexes FollowSymLinks
  Require all granted

  <LimitExcept OPTIONS>
    Require user y
    AuthType Digest
    AuthName "webdav"
    AuthUserFile /etc/httpd/conf/passwd
  </LimitExcept>

  Header always set Access-Control-Allow-Origin *
  Header always set Access-Control-Allow-Headers *
  Header always set Access-Control-Expose-Headers *
  Header always set Access-Control-Allow-Methods *
</Directory>
```
Yet I still got this error: 'I can't play this track because your browser didn't recognize it' when playing a song
<img width="249" alt="image" src="https://github.com/icidasset/diffuse/assets/13213464/608aa0cd-233b-428c-b15a-358cb23b7d2c">


seems the response never contains the audio
request:
<img width="1400" alt="image" src="https://github.com/icidasset/diffuse/assets/13213464/a05b6637-1bf1-4293-87ff-63436e6f9be1">
response:
<img width="1385" alt="image" src="https://github.com/icidasset/diffuse/assets/13213464/3f5efc59-2e0c-4e25-a88e-5e87c6bec4a5">

any idea about this?

**Comment by icidasset** [comment]
You're looking at the OPTIONS request, it's normal that this response is empty. In the case of browsers, the OPTIONS request serves as a preflight request in CORS. It's letting the browser know (through the response headers) which methods, origins and headers are allowed through CORS. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS for more info.

Can you send me the wireshark logs for that part?

Guess I should try it out myself just to be sure. How difficult is it to set up an Apache server nowadays?

By the way, any reason your using Apache specifically to set up a WebDAV server?

**Comment by ST-Saint** [comment]
[wireshark.zip](https://github.com/icidasset/diffuse/files/12841833/wireshark.zip)
Thanks for your help.

Actually there is no particular reason, but I had an apache webdav set up years ago and I want to reuse it if possible

**Comment by icidasset** [comment]
Hey again, sorry for the late response, I was sick for quite a while. It seems that there are only OPTION requests in the wireshark logs, so yeah it's normal the response is empty. 

Hard to say what otherwise could be the exact issue.

I'll give this a try myself at some point when I find some time.

**Comment by icidasset** [comment]
Hmm, my issue seems to be different than yours, because I guess in your case Diffuse did list the music, you just couldn't play it right?
