### ISSUE TITLE
The name

### ISSUE THREAD

**Issue by icidasset** [icidasset/diffuse#45]
Will be __Isotach__ for the next few months, after that I'll think again about renaming it.

Suggestions:
- Tapes (based on my original idea `Audiotapes`)
- Soundstack

**Comment by guylepage3** [comment]
This is awesome @icidasset I'll think about some more names this weekend and maybe even provide some very rough visuals this weekend. 👍

**Comment by guylepage3** [comment]
Hey @icidasset I just @ messaged you in the Blockstack Slack #design channel with the following message..

hey @icidasset i am about to update your latest icon and put it into the blockstack browser.

as a result i went to your latest link to the app.. https://isotach.io/

and i am blown away by your application.

:smile:

Love the demo

i am still wondering about the naming of the app however.. it totally does not match the application..

:disappointed:

in know we’ve talked about this in the past but i strongly feel this app deserves a name that would be worthy of the app. isotach for me just doesn’t measure up to the power and beauty of the application..

please let me know if we could chat about this more..

also, i am just playing around here with a couple of better icons/colors for you.

let me know your thoughts.

**Comment by guylepage3** [comment]
![app-icon-isotach-d1-256x256](https://user-images.githubusercontent.com/1711854/35169627-3321ba48-fd2b-11e7-8bea-e95f69cafd0b.png)

**Comment by icidasset** [comment]
Finally chose a name and decided on **Diffuse**.

**Comment by guylepage3** [comment]
Awesome news @icidasset ! 🙌🏻 Congrats and I love the name! Boom! 💥

**Comment by icidasset** [comment]
Thanks @guylepage3 ! ☺️
