### ISSUE TITLE
Get a decent logo

### ISSUE THREAD

**Issue by icidasset** [icidasset/diffuse#47]
~No ideas yet ¯\_(ツ)_/¯~

Is being worked on.

**Comment by guylepage3** [comment]
Hahaha.. I may have a few logos for you Steven. But I feel extremely strong that the name is a blocker.

**Comment by guylepage3** [comment]
Message me before you stop for the day and we'll see what I can put together quickly for you.

**Comment by icidasset** [comment]
Hah, thanks @guylepage3 ! I'm pretty busy this evening (in a few hours), so I'll message you tomorrow.

**Comment by guylepage3** [comment]
Sounds good sir.

**Comment by icidasset** [comment]
![diffuse-logo-blk](https://user-images.githubusercontent.com/296665/37063763-d36065f2-219a-11e8-89db-6987bb7df75d.png)

**Comment by guylepage3** [comment]
Looks good @icidasset. What does the App Icon look like sir? :)

**Comment by icidasset** [comment]
Thanks @guylepage3 ! 😄  The app icon looks like this:
![icon](https://user-images.githubusercontent.com/296665/37084359-90f69198-21f2-11e8-8895-8188569158bb.png)

Or alternatively:
![](https://diffuse.sh/images/icon.png)

**Comment by guylepage3** [comment]
NCIE!!!! This is super exciting stuff sir! 😄
