### ISSUE TITLE
Album art

### ISSUE THREAD

**Issue by icidasset** [icidasset/diffuse#66]
We previously tried to import all the album art, which worked but made everything slower than I wanted it to be. I also don't think it worked on mobile, it crashed the application because it was using too much memory.

So instead we might do something that shows the album art of the currently playing track?

**Comment by icidasset** [comment]
Idea: Don't store the album art with the tracks, instead store it locally in the browser or device (electron, PhoneGap).

**Comment by sunjam** [comment]
Would you do art through [Musicbrainz](https://musicbrainz.org)?  I see this Electron app called [Nuclear](https://electronjs.org/apps/nuclear) is using a combo of it with last.fm for album art.

**Comment by icidasset** [comment]
@sunjam Thanks for the suggestions! Good to know these are possibilities as well. I haven't decided yet which direction I'm going to take this.

On the one hand, I feel like, the fewer integrations with other services the better. I'm saying this because it's decentralized application. On the other hand, other services make some things a lot easier.

So yeah, I don't know yet.
Will let you know when I do.

**Comment by icidasset** [comment]
Idea:
Fetch album art when needed from the cache, and if it's not in the cache, get the tags and then the picture from that (or from musicbrainz if none exists). For example, get the album on the moment the cover element appears on screen, and then load it asynchronously.

**Comment by icidasset** [comment]
Finally implemented this one, will be in v3.
Available now on https://nightly.diffuse.sh if anyone wants to test it.
